apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: banking-microservices
spec:
  rules:
  - http:
      paths:
        - path: /customer/*
          backend:
            serviceName: customerapi-svc
            servicePort: 8001
        - path: /order/*
          backend:
            serviceName: orderapi-svc
            servicePort: 8001
